### ISSUE TITLE
Yahoo-signin LogRequest 

### ISSUE THREAD

**Issue by sonsy-soft** [dotnetzoom/RequestLogger-AspNetCore#6]
سلام 
آیا این امکان وجود داره که از کنترلر هایی که در کد اصلی برنامه قرار ندارن لاگ تهیه کنیم
Google-signin
Yahoo-signin
 که مربوط به لاگین خارجی هستن؟

**Comment by mjebrahimi** [comment]
سلام. خیر در این روش امکان پذیر نیست. (حداقل به سادگی)

نیاز شما رو میشه با یک Custom Middleware که ریکوئست های ورودی رو لاگ میکنه انجام داد
